<?php
/** v0.4.1 review reason taxonomy, Brief OS metadata, and run-linked usage contract. */
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__ . '/'); } if (!defined('ARRAY_A')) { define('ARRAY_A','ARRAY_A'); }
class WP_Error { private $c,$m,$d; function __construct($c='',$m='',$d=null){$this->c=$c;$this->m=$m;$this->d=$d;} function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} function get_error_data($c=''){return $this->d;} }
function is_wp_error($v){return $v instanceof WP_Error;} function sanitize_key($s){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$s));} function sanitize_text_field($s){return trim(preg_replace('/[\r\n\t]+/',' ',strip_tags((string)$s)));} function sanitize_textarea_field($s){return trim(strip_tags((string)$s));} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function current_time($t,$g=false){return $t==='timestamp'?1781352000:'2026-06-13 12:00:00';} function get_current_user_id(){return 31;} function get_option($k,$d=false){return $d;} function update_option($k,$v,$a=null){$GLOBALS['opts'][$k]=$v;return true;} function dbDelta($sql){$GLOBALS['ddl'][]=$sql;return[];} $GLOBALS['ddl']=[];$GLOBALS['opts']=[];
class FI_DB { public $prefix='wp_',$insert_id=0,$tables=[],$auto=[]; function get_charset_collate(){return'';} function prepare($sql,...$args){if(count($args)===1&&is_array($args[0]))$args=$args[0];foreach($args as$a){$sql=preg_replace_callback('/%[dsf]/',fn($m)=>$m[0]==='%d'?(string)(int)$a:($m[0]==='%f'?(string)(float)$a:"'".str_replace("'","''",(string)$a)."'"),$sql,1);}return$sql;} function insert($t,$r,$f=null){$id=($this->auto[$t]??0)+1;$this->auto[$t]=$id;$r['id']=$id;$this->tables[$t][$id]=$r;$this->insert_id=$id;return 1;} function get_var($sql){$r=$this->get_row($sql);return$r['id']??null;} function get_row($sql,$out=ARRAY_A){$r=$this->get_results($sql,$out);return$r[0]??null;} function get_results($sql,$out=ARRAY_A){if(!preg_match('/FROM\s+([a-zA-Z0-9_]+)/',$sql,$m))return[];$rows=array_values($this->tables[$m[1]]??[]);if(preg_match('/WHERE\s+(.+?)(?:\s+ORDER\s+BY|\s+LIMIT|$)/i',$sql,$wm)){foreach(preg_split('/\s+AND\s+/i',trim($wm[1]))as$p){$p=trim($p);if($p==='1=1')continue;if(!preg_match('/^([a-zA-Z0-9_]+)\s*=\s*(\'[^\']*\'|[0-9.\-]+)$/',$p,$cm))continue;$col=$cm[1];$raw=$cm[2];$val=(strlen($raw)>1&&$raw[0]==="'")?str_replace("''","'",substr($raw,1,-1)):$raw;$rows=array_values(array_filter($rows,fn($r)=>(string)($r[$col]??'')===(string)$val));}}if(preg_match('/ORDER\s+BY\s+id\s+DESC/i',$sql))usort($rows,fn($a,$b)=>(int)$b['id']<=>(int)$a['id']);if(preg_match('/LIMIT\s+([0-9]+)/i',$sql,$lm))$rows=array_slice($rows,0,(int)$lm[1]);return$rows;} }
$wpdb=new FI_DB();
class VES_Intelligence_Store { public static $created=[]; public static $insights=[11=>['id'=>11,'workspace_id'=>5,'run_id'=>101,'title'=>'Audience language gap','summary'=>'People ask for proof before tools.','recommendation'=>'Build an evidence-led LinkedIn angle.','evidence_ids'=>[501,502],'metadata'=>['message_angle'=>'proof_first']],12=>['id'=>12,'workspace_id'=>5,'title'=>'Unsupported idea','summary'=>'No evidence yet.','evidence_ids'=>[]]]; static function get_insight($id){return self::$insights[$id]??null;} static function find_brief_by_insight($w,$i){return 0;} static function create_brief($p){self::$created[]=$p;return count(self::$created);} }
class VES_Usage_Billing { public static $events=[]; static function record_meter_event($user_id,$event_type,$target_type,$target_id,$message,$context,$usage_key){if(isset(self::$events[$usage_key]))return self::$events[$usage_key]['id'];$id=count(self::$events)+1;self::$events[$usage_key]=compact('id','user_id','event_type','target_type','target_id','message','context','usage_key');return$id;} }
class VES_Decision_Edge_Service { public static $edges=[]; static function add_edge($workspace_id,$run_id,$from_type,$from_id,$to_type,$to_id,$relation_type,$args=[]){self::$edges[]=compact('workspace_id','run_id','from_type','from_id','to_type','to_id','relation_type','args');return count(self::$edges);} }
require_once dirname(__DIR__).'/includes/class-ves-review-decision-ledger.php'; require_once dirname(__DIR__).'/includes/class-ves-insight-brief-builder.php'; require_once dirname(__DIR__).'/includes/class-ves-usage-service.php';
$checks=0;$fails=[];function ok($c,$m){global$checks,$fails;$checks++;if(!$c){$fails[]=$m;fwrite(STDERR,"FAIL: $m\n");}}
VES_Review_Decision_Ledger::create_table(true); $ddl=implode("\n",$GLOBALS['ddl']); ok(strpos($ddl,'reason_code varchar(40)')!==false&&strpos($ddl,'KEY reason_code')!==false,'review migration adds reason_code'); ok(in_array('weak_evidence',VES_Review_Decision_Ledger::reason_codes(),true),'review reason taxonomy exposed');
$id=VES_Review_Decision_Ledger::record(['workspace_id'=>5,'object_type'=>'insight','object_id'=>11,'from_status'=>'draft','to_status'=>'approved','decision'=>'approve','reason_code'=>'good_angle','idempotency_key'=>str_repeat('a',64),'metadata'=>['prompt'=>'drop','source'=>'operator']]); ok(is_int($id)&&$id>0,'reason-coded decision records'); ok(VES_Review_Decision_Ledger::record(['workspace_id'=>5,'object_type'=>'insight','object_id'=>11,'decision'=>'approve','reason_code'=>'good_angle','idempotency_key'=>str_repeat('a',64)])===$id,'review idempotency works'); ok(is_int(VES_Review_Decision_Ledger::record(['workspace_id'=>5,'object_type'=>'draft','object_id'=>99,'decision'=>'reject'])),'decision without reason_code works'); ok(is_wp_error(VES_Review_Decision_Ledger::record(['workspace_id'=>5,'object_type'=>'draft','object_id'=>99,'decision'=>'reject','reason_code'=>'invented'])),'invalid reason_code rejected'); $recent=VES_Review_Decision_Ledger::recent(['workspace_id'=>5,'reason_code'=>'good_angle']); ok(count($recent)===1&&$recent[0]['reason_code']==='good_angle','recent filters reason_code'); $meta=json_decode($recent[0]['metadata'],true); ok(is_array($meta)&&!array_key_exists('prompt',$meta),'review metadata scrubs prompts');
$brief=VES_Insight_Brief_Builder::build_brief_from_insight(11,['run_id'=>202,'channel'=>'linkedin','format'=>'social_post','target_audience'=>'CMOs']); ok(is_array($brief)&&$brief['origin_type']==='insight'&&$brief['origin_id']===11,'brief carries insight origin'); ok($brief['run_id']===202&&$brief['source_evidence']===[501,502],'brief carries run and evidence'); ok($brief['channel']==='linkedin'&&$brief['format']==='social_post'&&$brief['target_audience']==='CMOs','brief carries channel/format/audience'); ok(is_wp_error(VES_Insight_Brief_Builder::build_brief_from_insight(12)),'unsupported insight brief blocked'); $manual=VES_Insight_Brief_Builder::build_manual_brief(['workspace_id'=>5,'run_id'=>303,'title'=>'Manual campaign','objective'=>'Test proof-led positioning.']); ok(is_array($manual)&&$manual['origin_type']==='manual'&&$manual['metadata']['manual_assumption_based'],'manual brief labeled assumption-based'); ok(VES_Insight_Brief_Builder::create_manual_brief($manual)===1,'manual brief delegates to store');
$u=VES_Usage_Service::record_zero_cost_event(['workspace_id'=>5,'run_id'=>202,'target_type'=>'draft','target_id'=>808,'event_type'=>'manual_preview','idempotency_key'=>'fi:usage:202:808']); ok($u===1,'zero-cost usage records'); $u2=VES_Usage_Service::record_zero_cost_event(['workspace_id'=>5,'run_id'=>202,'target_type'=>'draft','target_id'=>808,'event_type'=>'manual_preview','idempotency_key'=>'fi:usage:202:808']); ok($u2===$u&&count(VES_Usage_Billing::$events)===1,'usage idempotency prevents duplicate'); $event=current(VES_Usage_Billing::$events); ok((int)$event['context']['charged_credits']===0&&(string)$event['context']['run_id']==='202','zero-cost usage carries run and no charge'); ok(count(VES_Decision_Edge_Service::$edges)>=1&&VES_Decision_Edge_Service::$edges[0]['relation_type']==='spent_usage','usage writes decision edge'); ok(is_wp_error(VES_Usage_Service::record_zero_cost_event(['workspace_id'=>5,'target_type'=>'draft','target_id'=>808])),'usage refuses missing run');
if($fails){fwrite(STDOUT,sprintf("v0.4.1 review/brief/usage checks: %d passed, %d failed\n",$checks-count($fails),count($fails)));exit(1);} fwrite(STDOUT,"v0.4.1 review/brief/usage checks passed: $checks / $checks\n");
