<?php
/** v0.4.1 canonical Run, Decision Edge, Outcome, and Pattern store contract. */
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__ . '/'); }
if (!defined('ARRAY_A')) { define('ARRAY_A', 'ARRAY_A'); }
class WP_Error { private $c,$m,$d; function __construct($c='',$m='',$d=null){$this->c=$c;$this->m=$m;$this->d=$d;} function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} function get_error_data($c=''){return $this->d;} }
function is_wp_error($v){return $v instanceof WP_Error;} function sanitize_key($s){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$s));} function sanitize_text_field($s){return trim(preg_replace('/[\r\n\t]+/',' ',strip_tags((string)$s)));} function sanitize_textarea_field($s){return trim(strip_tags((string)$s));} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function current_time($t,$g=false){return $t==='timestamp'?1781352000:'2026-06-13 12:00:00';} function get_current_user_id(){return 23;} function get_option($k,$d=false){return $d;} function update_option($k,$v,$a=null){$GLOBALS['opts'][$k]=$v;return true;} function dbDelta($sql){$GLOBALS['ddl'][]=$sql;return[];} $GLOBALS['ddl']=[];$GLOBALS['opts']=[];
class FI_DB { public $prefix='wp_',$insert_id=0,$tables=[],$auto=[]; function get_charset_collate(){return'';} function prepare($sql,...$args){if(count($args)===1&&is_array($args[0]))$args=$args[0];foreach($args as $a){$sql=preg_replace_callback('/%[dsf]/',fn($m)=>$m[0]==='%d'?(string)(int)$a:($m[0]==='%f'?(string)(float)$a:"'".str_replace("'","''",(string)$a)."'"),$sql,1);}return$sql;} function query($sql){return true;} function insert($t,$r,$f=null){$id=($this->auto[$t]??0)+1;$this->auto[$t]=$id;$r['id']=$id;$this->tables[$t][$id]=$r;$this->insert_id=$id;return 1;} function update($t,$r,$w,$f=null,$wf=null){$n=0;foreach(($this->tables[$t]??[])as$id=>$row){$ok=true;foreach($w as$k=>$v){if((string)($row[$k]??'')!==(string)$v){$ok=false;break;}}if($ok){$this->tables[$t][$id]=array_merge($row,$r);$n++;}}return$n;} function get_row($sql,$out=ARRAY_A){$r=$this->get_results($sql,$out);return$r[0]??null;} function get_results($sql,$out=ARRAY_A){if(!preg_match('/FROM\s+([a-zA-Z0-9_]+)/',$sql,$m))return[];$rows=array_values($this->tables[$m[1]]??[]);if(preg_match('/WHERE\s+(.+?)(?:\s+ORDER\s+BY|\s+LIMIT|$)/i',$sql,$wm)){foreach(preg_split('/\s+AND\s+/i',trim($wm[1]))as$p){$p=trim($p);if($p==='1=1')continue;if(!preg_match('/^([a-zA-Z0-9_]+)\s*=\s*(NULL|\'[^\']*\'|[0-9.\-]+)$/',$p,$cm))continue;$col=$cm[1];$raw=$cm[2];$val=$raw==='NULL'?null:((strlen($raw)>1&&$raw[0]==="'")?str_replace("''","'",substr($raw,1,-1)):$raw);$rows=array_values(array_filter($rows,fn($r)=>$val===null?(!isset($r[$col])||$r[$col]===null):(string)($r[$col]??'')===(string)$val));}}if(preg_match('/ORDER\s+BY\s+id\s+DESC/i',$sql))usort($rows,fn($a,$b)=>(int)$b['id']<=>(int)$a['id']);elseif(preg_match('/ORDER\s+BY\s+id\s+ASC/i',$sql))usort($rows,fn($a,$b)=>(int)$a['id']<=>(int)$b['id']);elseif(preg_match('/ORDER\s+BY\s+last_seen_at\s+DESC/i',$sql))usort($rows,fn($a,$b)=>strcmp((string)($b['last_seen_at']??''),(string)($a['last_seen_at']??'')));if(preg_match('/LIMIT\s+([0-9]+)/i',$sql,$lm))$rows=array_slice($rows,0,(int)$lm[1]);return$rows;} }
$wpdb=new FI_DB();
require_once dirname(__DIR__).'/includes/class-ves-run-store.php'; require_once dirname(__DIR__).'/includes/class-ves-run-service.php'; require_once dirname(__DIR__).'/includes/class-ves-decision-edge-store.php'; require_once dirname(__DIR__).'/includes/class-ves-decision-edge-service.php'; require_once dirname(__DIR__).'/includes/class-ves-outcome-store.php'; require_once dirname(__DIR__).'/includes/class-ves-outcome-service.php'; require_once dirname(__DIR__).'/includes/class-ves-pattern-observation-store.php';
$checks=0;$fails=[];function ok($c,$m){global$checks,$fails;$checks++;if(!$c){$fails[]=$m;fwrite(STDERR,"FAIL: $m\n");}}
VES_Run_Store::create_table(true); ok(strpos(implode("\n",$GLOBALS['ddl']),'ves_intel_runs')!==false,'run migration DDL emitted');
$run=VES_Run_Service::create_run(['workspace_id'=>3,'source_id'=>44,'input_context'=>['language'=>'en'],'idempotency_key'=>'source:44']); ok(is_int($run)&&$run>0,'run created'); ok(VES_Run_Service::create_run(['workspace_id'=>3,'idempotency_key'=>'source:44'])===$run,'run idempotency reuses existing');
$row=VES_Run_Service::get_run($run); ok($row['input_context']['language']==='en'&&$row['source_id']===44,'run JSON/source round trip'); ok(VES_Run_Service::mark_running($run)===$run&&VES_Run_Service::mark_completed($run,['signals'=>2])===$run,'run status transitions complete'); ok(is_wp_error(VES_Run_Service::mark_failed($run,'late')),'terminal run cannot reopen'); ok(VES_Run_Service::assert_workspace($run,3)===true&&is_wp_error(VES_Run_Service::assert_workspace($run,4)),'run workspace assertion enforced');
VES_Decision_Edge_Store::create_table(true); ok(strpos(implode("\n",$GLOBALS['ddl']),'ves_decision_edges')!==false,'edge migration DDL emitted');
$edge=VES_Decision_Edge_Service::add_edge(3,$run,'signal',10,'insight',20,'supports',['evidence_refs'=>[['evidence_id'=>99]],'metadata'=>['token'=>'secret','note'=>'ok']]); ok(is_int($edge)&&$edge>0,'edge appended'); ok(is_wp_error(VES_Decision_Edge_Service::add_edge(3,$run,'signal',10,'insight',20,'bad_relation')),'bad relation rejected');
$edges=VES_Decision_Edge_Service::list_edges_for_run(3,$run); ok(count($edges)===1&&$edges[0]['evidence_refs'][0]['evidence_id']===99,'edge list by run + evidence JSON round trip'); ok(count(VES_Decision_Edge_Service::list_edges_for_target(3,'insight',20))===1&&count(VES_Decision_Edge_Service::list_edges_for_run(9,$run))===0,'edge target lookup and workspace scope');
VES_Outcome_Store::create_table(true); $out=VES_Outcome_Service::record_outcome(['workspace_id'=>3,'run_id'=>$run,'target_type'=>'draft','target_id'=>77,'outcome_type'=>'manual_note','qualitative_note'=>'Client approved','metrics'=>['engagement_rate'=>0.04],'result_label'=>'won']); ok(is_int($out)&&$out>0,'manual outcome recorded'); ok(count(VES_Outcome_Service::list_for_target(3,'draft',77))===1,'outcome list by target'); ok(is_wp_error(VES_Outcome_Service::record_outcome(['workspace_id'=>3,'target_type'=>'draft','target_id'=>1])),'empty outcome rejected');
VES_Pattern_Observation_Store::create_table(true); $pat=VES_Pattern_Observation_Store::record_pattern(['workspace_id'=>3,'run_id'=>$run,'pattern_key'=>'linkedin_hook_risk','success_count'=>2,'trial_count'=>3,'source_refs'=>[['outcome_id'=>$out]]]); ok(is_int($pat)&&$pat>0,'pattern with source refs recorded'); ok(is_wp_error(VES_Pattern_Observation_Store::record_pattern(['workspace_id'=>3,'pattern_key'=>'no_refs'])),'pattern without source refs rejected');
if($fails){fwrite(STDOUT,sprintf("v0.4.1 canonical spine checks: %d passed, %d failed\n",$checks-count($fails),count($fails)));exit(1);} fwrite(STDOUT,"v0.4.1 canonical spine checks passed: $checks / $checks\n");
